### ISSUE TITLE
1.11.0 fails installation via npm

### ISSUE THREAD

**Issue by dhelleberg** [ios-control/ios-deploy#465] opened 2020-07-09 20:16 UTC
run 
`npm install -g ios-deploy --unsafe-perm=true `

# Expected behavior

installation successfull

# Actual behavior.

```
 sh: line 1: 19611 Illegal instruction: 4  xcodebuild
 npm ERR! code ELIFECYCLE
 npm ERR! errno 132
 npm ERR! ios-deploy@1.11.0-beta.1 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
 npm ERR! Exit status 132

```
# Steps to reproduce the problem

run `npm install -g ios-deploy --unsafe-perm=true  `
on OSX 10.14.6

Workaround: run 
`npm install -g ios-deploy@1.10.0 --unsafe-perm=true`

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G4032)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Mac mini 2018
      User Name: 
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 42 days 11:33
- [ ] 2. ios-deploy -V
- [x] 3. xcodebuild -version
xcodebuild -version
Xcode 11.3.1
Build version 11C505

- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version

**Comment by gabebear** [comment] 2020-07-10 14:17
Thanks for the report! This is a two parter:

1. **Npmjs installing beta version by default** - I had tagged the npmjs releases improperly. I've fixed that so the default it now 1.10.0 again. https://www.npmjs.com/package/ios-deploy?activeTab=versions `npm install -g ios-deploy --unsafe-perm=true` will install 1.10.0 again and the beta version is 1.11.0-beta.1
1. **Beta Failing to Install** - I'm not sure why the beta is failing yet, but I can reproduce a script failure on Catalina with Xcode 10.3(but that it works on Xcode 11.5 and Xcode 12-beta).

The npm default version problem should now be resolved, but I'm leaving this issue open to look into why the beta version is failing with older Xcode versions on Catalina.

**Comment by gabebear** [comment] 2020-07-10 17:10
I looked at this a bit more and the issue isn't the version of Xcode, it's that the file permissions to build are wrong if you are running with `sudo`... which is a bug I'm tempted to say is a feature.

Running `npm install` as root is never a good idea. https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

As for covering use-cases:
 - **System-wide tool** - e.g. running ios-deploy in the terminal
    - npm doesn't support installing global tools very well(it is possible without sudo, but the defaults make it a pain)
    - [Homebrew](https://brew.sh/) is generally better suited(e.g. not a pain to setup) and is already supported by ios-deploy
        - `brew install ios-deploy` <- install stable version
        - `brew install --HEAD ios-deploy` <- install latest dev version from source
- **Node dependencies** - cases where ios-deploy is a dependency of another package
    - Users using `sudo npm install -g ` to install existing packages that have a dependency on ios-deploy will fail. This is not great, but generally using sudo this way is an [antipattern](https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92) that the user can resolve by not using sudo(e.g. using npx).
    - Building/Installing ios-deploy via npm without sudo works properly, so non-sudo uses seem to be working as intended.

I think the best option here is to add a check in our build script telling people to never run npm as root and document that this doesn't work after version 1.10.0.

**Comment by gabebear** [comment] 2020-07-10 17:39
@dhelleberg I was verifying on Catalina(I don't have a Mojave machine). Can you reproduce this without using sudo?

**Comment by SeekingMeaning** [comment] 2020-07-10 19:03
Can confirm that the current tag for 1.11.0 builds on macOS 10.13, 10.14, and 10.15

I was in the process of updating the ios-deploy formula to 1.11.0, and Homebrew builds packages before they are updated (See Homebrew/homebrew-core#57811)

(I noticed that the 1.11.0-beta.1 tag is basically the same as 1.11.0 so this should still apply)

Also, is 1.11.0 considered to be a pre-release version? I may have mistook it for a stable version when I saw the 1.11.0 tag after 1.11.0-beta.1

**Comment by dhelleberg** [comment] 2020-07-10 21:09
> @dhelleberg I was verifying on Catalina(I don't have a Mojave machine). Can you reproduce this without using sudo?

I'm not running this as root or sudo. Do you need any additional information?

**Comment by gabebear** [comment] 2020-07-13 17:32
@dhelleberg  I would like to know if it is npm related or 10.14 related. Can you try installing the latest ios-deploy via homebrew with `brew install --HEAD ios-deploy`. Using `--HEAD` will build ios-deploy locally via Homebrew.

The Homebrew backend appears to build ios-deploy properly on macOS 10.13, 10.14, and 10.15 https://github.com/Homebrew/homebrew-core/pull/57811

**Comment by gabebear** [comment] 2020-07-16 14:52
@dhelleberg have you tried compiling/installing ios-deploy from HEAD via Homebrew?
```
brew install --HEAD ios-deploy
```

**Comment by dhelleberg** [comment] 2020-07-18 20:56
Sorry for the late reply. Installation via brew is working, seems to be npm related

**Comment by gabebear** [comment] 2020-07-24 14:11
I'm not at all sure why npm is failing in this case, but I can't reproduce it and it's not blocking anyone that I know of.

I'm going to close this since I think it's an edge case, but if this can be reproduced on Catalina I would welcome it to be re-opened.

**Comment by mcfarljw** [comment] 2020-07-26 12:54
I also ran into this issue as well when trying to update to `1.11.0`, but after updating node from `12.18.1` to `12.18.3` it installed correctly.

**Comment by gabebear** [comment] 2020-07-26 18:20
Reopening since this is happening on Catalina https://github.com/ios-control/ios-deploy/issues/466

Someone who is willing to fix it needs to reproduce it(I probably won’t have time for awhile)

**Comment by gabebear** [comment] 2020-07-27 13:32
This likely has something to do with https://github.com/ios-control/ios-deploy/issues/450

**Comment by hp-phuoclh** [comment] 2020-07-30 03:45
@gabebear 

I have an error while update with ` brew upgrade ios-deploy`

```
** BUILD FAILED **


The following build commands failed:
	Ld /tmp/ios-deploy-20200730-28386-fz03c3/ios-deploy-1.11.0/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/arm64/Binary/ios-deploy normal arm64
(1 failure)

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

```

**Comment by gabebear** [comment] 2020-07-31 13:11
@hp-phuoclh  What version of BigSur(macOS 11.0) are you using? I only have it on my DTK(Apple Silicon).

**Comment by gabebear** [comment] 2020-07-31 16:39
@hp-phuoclh I opened a new issue with a workaround for what you are seeing
https://github.com/ios-control/ios-deploy/issues/467

**Comment by gabebear** [comment] 2020-08-06 16:56
I'm closing this since updating to node 12.18.3 seems to fix the npm issue.

**Closed by gabebear** 2020-08-06 16:56 UTC
Labels: bug
