### ISSUE TITLE
sudo npm install -g ios-deploy --unsafe-perm=true   

### ISSUE THREAD

**Issue by DemoDu** [ios-control/ios-deploy#347] opened 2018-07-02 06:53 UTC
sudo npm install -g ios-deploy --unsafe-perm=true  
使用此命令安装也是失败的
xcode version 9.4.1 
macos   10.13.5

**Comment by WarriorsWCH** [comment] 2018-07-12 03:43
me too

**Comment by WarriorsWCH** [comment] 2018-07-12 03:44
Have you solved it

**Comment by paolostefan** [comment] 2018-07-13 14:00
Same problem, same MacOS version.
The error I get is:

```
cp: /System/Library/PrivateFrameworks/MobileDevice.framework/XPCServices: No such file or directory

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script build/ios-deploy.build/Release/ios-deploy.build/Script-C0CD3D981F59D20100F954DB.sh
```

**Comment by ChanJianxun** [comment] 2018-07-23 03:14
Me too.

**Comment by shazron** [comment] 2018-07-24 04:45
Closing as dupe of #349 (resolution there)

**Closed by shazron** 2018-07-24 04:45 UTC

**Comment by isma3l** [comment] 2022-03-31 19:56
Thanks!!! :)
