### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by timatoe** [ios-control/ios-deploy#353] opened 2018-07-22 05:45 UTC
Build fails when installing ios-deploy using brew
`brew install ios-deploy`

This is the error message: 
```
** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/ios-deploy-20180722-38145-bnmlsx/ios-deploy-1.9.2/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy.o /tmp/ios-deploy-20180722-38145-bnmlsx/ios-deploy-1.9.2/src/ios-deploy/ios-deploy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

# Getting the following behavior:
```
==> Downloading https://github.com/phonegap/ios-deploy/archive/1.9.2.tar.gz
Already downloaded: /Users/xxx/Library/Caches/Homebrew/ios-deploy-1.9.2.tar.gz
==> xcodebuild -configuration Release SYMROOT=build
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/ios-deploy/01.xcodebuild:
: missing terminating '"' character [-Winvalid-pp-token]
"
^
2 warnings and 1 error generated.
```

# Steps to reproduce the problem
run `brew install ios-deploy` in terminal

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [X] 1. system_profiler SPSoftwareDataType
```
System Software Overview:

      System Version: macOS 10.14 (18A336e)
      Kernel Version: Darwin 18.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: xxx's MacBook Pro
      User Name: xxx (xxx)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 16:19
```

- [X] 2. ios-deploy -V
```
N/A
```

- [X] 3. xcodebuild -version
```
Xcode 10.0
Build version 10L213o
```

- [X] 4. xcode-select --print-path
```
/Applications/Xcode-beta.app/Contents/Developer
```

- [X] 5. gcc --version
```
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.40.1)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

- [X] 6. lldb --version
```
lldb-1000.0.31
  Swift-4.2
```

**Comment by shazron** [comment] 2018-07-24 03:40
sorry, we don't publish to brew -- someone else does that independently. We only publish to npm.

**Comment by shazron** [comment] 2018-07-24 04:40
In any case I ran xcodebuild and I can't repro this specific issue.

**Comment by shazron** [comment] 2018-07-24 04:42
Might be an Xcode 10/beta thing

**Comment by shazron** [comment] 2018-07-24 04:43
Closing as a dupe of #350

**Closed by shazron** 2018-07-24 04:43 UTC
Labels: bug

**Comment by shazron** [comment] 2018-07-24 07:50
1.9.3 published with this fix: https://github.com/ios-control/ios-deploy/releases/tag/1.9.3
